### ISSUE TITLE
upgrade 'num' to 'unsigned'

### ISSUE THREAD

**Issue by VitaliyaIoffe** [tarantool/cbench#8]
There are a lot of warnings during execution 

`main/103/cbench_runner.lua schema.lua:1249 W> field type 'num' is deprecated since Tarantool 1.7, please use 'unsigned' instead`

**Comment by Totktonada** [comment]
NB: https://github.com/tarantool/expirationd/pull/81#discussion_r715538421

However the `'num'` → `'number'` recommendation is for modules / applications. Here 1) we aren't interested in old snapshots; 2) actually operate on unsigned integer; so it should be okay to actually replace `'num'` with `'unsigned'`.
